version : '3'

services:
  adminer:
    image: adminer
    ports:
      - 8080:8080

  authenticationDatabase:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"] # we ping the database to check is it initialized
      timeout: 10s
      retries: 20

  authenticationDBMigration:
    image: authenticationdbmigration
    environment:
      - DATABASE_URL=authenticationDatabase
    depends_on:
      authenticationDatabase:
        condition: service_healthy

  authentication:
    image: authentication
    environment:
      - DATABASE_URL=authenticationDatabase
    depends_on:
      - authenticationDBMigration
    ports:
      - 5002:5002
