version : '3'

services:
  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - adminernet

  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - redisnet

  # AUTHENTICATION SUBSYSTEM

  authenticationDatabase:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
    networks:
      - authnet
      - adminernet
    volumes:
      - authdbvolume:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"] # we ping the database to check is it initialized
      timeout: 10s
      retries: 20

  authenticationDBMigration:
    image: authenticationdbmigration
    environment:
      - DATABASE_URL=authenticationDatabase
    networks:
      - authnet
    depends_on:
      authenticationDatabase:
        condition: service_healthy

  authentication:
    image: authentication
    environment:
      - DATABASE_URL=authenticationDatabase
    networks:
      - authnet
    depends_on:
      - authenticationDBMigration
    ports:
      - 5002:5002

  # SHOP SUBSYSTEM

  shopDatabase:
    image:
      mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3307:3306
    networks:
      - buyernet
      - adminnet
      - daemonnet
      - adminernet
    volumes:
      - shopdbvolume:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ] # we ping the database to check is it initialized
      timeout: 10s
      retries: 20

  shopDBMigration:
    image: shopdbmigration
    environment:
      - DATABASE_URL=shopDatabase
    networks:
      - buyernet
      - adminnet
      - daemonnet
    depends_on:
      shopDatabase:
        condition: service_healthy

  buyer:
    image: buyer
    environment:
      - DATABASE_URL=shopDatabase
    ports:
      - 5003:5003
    networks:
      - buyernet
    depends_on:
      - shopDBMigration

  admin:
    image: admin
    environment:
      - DATABASE_URL=shopDatabase
    ports:
      - 5004:5004
    networks:
      - adminnet
    depends_on:
      - shopDBMigration

  warehouse:
    image: warehouse
    ports:
      - 5001:5001
    environment:
      - REDIS_HOST=redis
    networks:
      - warehousenet
      - redisnet

  daemon:
    image: daemon
    environment:
      - DATABASE_URL=shopDatabase
      - REDIS_HOST=redis
    networks:
      - daemonnet
      - redisnet
    depends_on:
      - shopDBMigration


networks:
  authnet:

  buyernet:

  adminnet:

  warehousenet:

  daemonnet:

  adminernet:

  redisnet:


# virtual disks for containers
volumes:
  authdbvolume:

  shopdbvolume:

