version : '3'

services:
  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - adminernetauth
      - adminernetshop

  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - redisnetdaemon
      - redisnetwarehouse

  # AUTHENTICATION SUBSYSTEM

  authenticationDatabase:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
    networks:
      - authnet
      - adminernetauth
    volumes:
      - authdbvolume:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"] # we ping the database to check is it initialized
      timeout: 10s
      retries: 20

  authenticationDBMigration:
    image: authenticationdbmigration
    environment:
      - DATABASE_URL=authenticationDatabase
    networks:
      - authnet

  authentication:
    image: authentication
    environment:
      - DATABASE_URL=authenticationDatabase
    networks:
      - authnet
    ports:
      - 5002:5002

  # SHOP SUBSYSTEM

  shopDatabase:
    image:
      mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3307:3306
    networks:
      - buyernet
      - adminnet
      - daemonnet
      - adminernetshop
    volumes:
      - shopdbvolume:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ] # we ping the database to check is it initialized
      timeout: 10s
      retries: 20

  shopDBMigration:
    image: shopdbmigration
    environment:
      - DATABASE_URL=shopDatabase
    networks:
      - buyernet
      - adminnet
      - daemonnet

  buyer:
    image: buyer
    environment:
      - DATABASE_URL=shopDatabase
    ports:
      - 5003:5003
    networks:
      - buyernet
    deploy:
      replicas: 3

  admin:
    image: admin
    environment:
      - DATABASE_URL=shopDatabase
    ports:
      - 5004:5004
    networks:
      - adminnet

  warehouse:
    image: warehouse
    ports:
      - 5001:5001
    environment:
      - REDIS_HOST=redis
    networks:
      - warehousenet
      - redisnetwarehouse
    deploy:
      replicas: 3

  daemon:
    image: daemon
    environment:
      - DATABASE_URL=shopDatabase
      - REDIS_HOST=redis
    networks:
      - daemonnet
      - redisnetdaemon


networks:
  authnet:
    driver: overlay

  buyernet:
    driver: overlay

  adminnet:
    driver: overlay

  warehousenet:
    driver: overlay

  daemonnet:
    driver: overlay

  adminernetauth:
    driver: overlay

  adminernetshop:
    driver: overlay

  redisnetwarehouse:
    driver: overlay

  redisnetdaemon:
    driver: overlay

# virtual disks for containers
volumes:
  authdbvolume:

  shopdbvolume:

